version: '3.7'

services:
  django:
    container_name: dj
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env_template
    ports:
      - "8080:8000"
    networks:
      - django

volumes:
  staticfiles:
  mediafiles:

networks:
  django:
    external: true